resources:
- name: cf-hello-env
  type: git
  source:
    uri: https://github.com/jamesjoshuahill/hello-env.git
    branch: master

- name: cf-warden
  type: cf
  source:
    api: http://api.10.244.0.34.xip.io
    username: admin
    password: admin
    organization: sample
    space: sample
    skip_cert_check: true

jobs:
- name: cf-hello-env-unit
  plan:
  - get: cf-hello-env
    trigger: true
  - task: unit
    privileged: true
    config:
      platform: linux
      image: docker:///cloudcredo/ccp
      inputs:
      - name: cf-hello-env
        path: .
      run:
        path: ./test.sh

- name: deploy-cf-hello-env-unit
  plan:
  - get: cf-hello-env
    trigger: true
    passed:
    - cf-hello-env-unit
  - put: cf-warden
    params:
      manifest: cf-hello-env/manifest.yml
  serial_groups:
  - deploy-cf-hello-env-unit
